### ISSUE TITLE
ERROR: ArrayIndexOutOfBound

### ISSUE THREAD

**Issue by hannanmax** [roshan-nyk/INSTANT_SAVER_FOR_INSTAGRAM#1]
java.lang.RuntimeException: Unable to start activity ComponentInfo{instant.saver.for_instagram/instant.saver.for_instagram.InstagramActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=2

**Comment by roshan-nyk** [comment]
The code will not work unless you add your own cookies.
If you need any help then reply me back.

**Comment by hannanmax** [comment]
> The code will not work unless you add your own cookies. If you need any help then reply me back.

Can I text you on WhatsApp, I want to know how to implement Instagram GraphApi and where should I change app id and key in your app.
