### ISSUE TITLE
application is going crashed

### ISSUE THREAD

**Issue by Rohitrajkhorwal** [roshan-nyk/INSTANT_SAVER_FOR_INSTAGRAM#3]
Every time app crash
Mediaview and Saved item list not working

**Comment by roshan-nyk** [comment]
Kindly update the app. The updated version is 1.1.0
Even after that the error persist then you can respond me back on this thread. Thank you

**Comment by Rohitrajkhorwal** [comment]
**some Changes in MediFragment**
**Line 599 to 603**
`        try {
            userDetails.add(photoModel.getNode().getOwner().getUsername());
            userDetails.add(savedProfilePicUrl);
            userDetails.add(photoModel.getNode().getShortcode());
            userDetails.add(photoModel.getNode().getEdgeMediaToCaption().getEdges().get(0).getNode().getText());
            userDetails.add("p");
        }
        catch (Exception e){
            userDetails.add(photoModel.getNode().getOwner().getUsername());
            userDetails.add(savedProfilePicUrl);
            userDetails.add(photoModel.getNode().getShortcode());
//            userDetails.add(photoModel.getNode().getEdgeMediaToCaption().getEdges().get(0).getNode().getText());
            userDetails.add("p");
        }`

**// if posts caption not available app is going crash so put photoModel code in try catch method**

`@Override
    public void onDestroyView() {
        if (viewPagerPositionsToDownload.size() > 0 && totalRequiredDownloads != -5) {
            ArrayList<String> userDetails = new ArrayList<>();
            if (storyItemModelList != null) {
                userDetails.add(userName);
                userDetails.add(savedProfilePicUrl);
                userDetails.add(null);
                userDetails.add(null);
                userDetails.add(null);
            } else if (photoModel != null) {
                try{
                    userDetails.add(photoModel.getNode().getOwner().getUsername());
                    userDetails.add(savedProfilePicUrl);
                    userDetails.add(photoModel.getNode().getShortcode());
                    userDetails.add(photoModel.getNode().getEdgeMediaToCaption().getEdges().get(0).getNode().getText());
                    userDetails.add("p");
                }
                catch (Exception e){
                    userDetails.add(photoModel.getNode().getOwner().getUsername());
                    userDetails.add(savedProfilePicUrl);
                    userDetails.add(photoModel.getNode().getShortcode());
//                    userDetails.add(photoModel.getNode().getEdgeMediaToCaption().getEdges().get(0).getNode().getText());
                    userDetails.add("p");
                }
            }
//            download process starting before destroying fragment
            utils.checkAvailableExternalStorage(stringsUrlsToDownload, userDetails, albumData, isVideoList);
        }
        if (currentVisibleAlbumDataOnViewPager2 != null)
            currentVisibleAlbumDataOnViewPager2 = null;
        if (albumDataViewModel.getAllMedias() != null)
            albumDataViewModel.getAllMedias().removeObservers(requireActivity());
        super.onDestroyView();
    }`

**Comment by roshan-nyk** [comment]
try catch will not work here as  I have tried. If capton is not present then you  have to send null instead of it. You can check the particular part of the code again. I have mentioned the condition for that. And now it's working on the app also.
Version 1.1.3
Thanks for Sharing where the error was happening.
