### ISSUE TITLE
Access Instagram data Problem

### ISSUE THREAD

**Issue by Rohitrajkhorwal** [roshan-nyk/INSTANT_SAVER_FOR_INSTAGRAM#5]
what's the problem with the app.
**unable to Access Instagram data appears each time.** 
My internet is working fine.
Profile is not bookmarked. Copy link does not downloading.

**Comment by Rohitrajkhorwal** [comment]
**It was working a few days ago. Now have to clear cache every time**

**Comment by hannanmax** [comment]
I am facing the same problem, i cannot add users to bookmark anymore.
