### ISSUE TITLE
UNABLE TO ACCESS INSTAGRAM

### ISSUE THREAD

**Issue by hannanmax** [roshan-nyk/INSTANT_SAVER_FOR_INSTAGRAM#6]
what's the problem with the app.
unable to Access Instagram data appears each time.
My internet is working fine.
The profile is not bookmarked. Copy link does not download.

**Comment by roshan-nyk** [comment]
While requesting for downloading a file using copied link it is not returning a json response. Instaed we are getting back a html response.  But if i open the same link on browser/postman we get a json as response. I am not getting what is the reason behind it. This is same for all those bookmark, download. 
But if u have logged in for this app and an user  trying to download media files from inside the app, It is working smoothly.

Is there anyone who can share his knowledge regarding this particular type of problem, if they have faced or have knowledge about how to tackle this?

**Comment by roshan-nyk** [comment]
@Rohitrajkhorwal check ur profile. I have sent you an invitation. The thing is we are not getting response as a json, but as a html. That's why i am not able to decode. Check it. If you can resolve this issue then I would be really helpful.
